import assert from "node:assert/strict";
import { calculate, adjustedWin, mintRate, preset } from "../src/paper/model";
import { configured, paperConfig } from "../src/paper/config";
import { transition, type Journal } from "../src/paper/machine";
import { RelayerAdapter } from "../src/paper/relayer";
const checks: string[] = [];
function close(actual: number, expected: number, tolerance = 1e-6) { assert(Math.abs(actual - expected) < tolerance, `${actual} != ${expected}`); }
const p = calculate(preset);
close(p.margin, 400); close(p.notional, 10000); close(p.loss, 100);
close(p.adjusted, 88.1469167182); close(p.win, 86.3839783838);
close(p.paper, 9800); close(p.pairCost, 13.6160216158); close(p.bustMove, .0395);
close(p.netCost, 14.6160216158); close(p.cashAtRisk, 101);
checks.push("Report worked pair: $400 margin, $10,000 notional, 9,800 PAPER and $13.616022 pair cost; activation counted once.");
const report = calculate({ ...preset, deposit: 1000, firstDeposit: false });
close(report.costPerPaper!, .001389389961);
close(adjustedWin(10000, 0, "BTC"), 0); close(adjustedWin(10000, 1/50000, "BTC"), 0);
assert.equal(calculate({ ...preset, movePercent: 0 }).costPerPaper, null);
assert(calculate({ ...preset, market: "ETH" }).costPerPaper! > p.costPerPaper!);
close(calculate({ ...preset, deposit: 2000, firstDeposit: false }).costPerPaper!, report.costPerPaper!);
checks.push("Deadband boundary, no-mint undefined cost, BTC/ETH impact ordering and scale invariance.");
const active = calculate({ ...preset, queue: "active", stakePercent: 20 });
close(active.paper, 10000); close(active.rebate, 0);
close(calculate({ ...preset, queue: "thin", closeOrder: "winner-first" }).paper, 10000);
close(calculate({ ...preset, queue: "thin", closeOrder: "loser-first" }).paper, 9800);
close(calculate({ ...preset, stakePercent: 20 }).rebate, .3762938334);
close(calculate({ ...preset, recoveryPercent: 0 }).discountedCost, 101);
close(calculate({ ...preset, recoveryPercent: 50 }).discountedCost, 57.808010808);
checks.push("Queue 1.0 / solvent 0.98 loss basis, close order, paid-rebate suppression, 20% stake and recovery discount.");
close(mintRate(0), 100); close(mintRate(30000000), 64); close(mintRate(100000000), 29.7520661157); close(mintRate(120000000), 25);
close(calculate({ ...preset, mintRegime: "tail", tailProgress: 120000000 }).paper, 2450);
const bust = calculate({ ...preset, leverage: 1000, movePercent: 1 });
assert(bust.liquidated); close(bust.basis, bust.margin); close(bust.effectiveMove, .00052);
checks.push("Mint tail examples and full-margin hard-bust basis at approximate trigger, not requested later target.");
for (const patch of [{ deposit: 0 }, { deposit: 10 }, { deposit: NaN }, { leverage: 1001 }, { leverage: 0 }, { movePercent: -1 }, { allocationPercent: 101 }, { inbound: -1 }, { recoveryPercent: 101 }, { stakePercent: -1 }, { deposit: 1e9 }]) assert.throws(() => calculate({ ...preset, ...patch }));
close(calculate({ ...preset, currency: "ETH", deposit: 1, ethPrice: 3000, inbound: 5, outbound: 5 }).balance, 2994);
checks.push("Input bounds, first-arrival minimum, $10M notional cap and ETH route-cost model.");
assert.equal(configured(), false);
assert(Object.values(paperConfig.addresses).every(v => v === null));
let networkCalls = 0;
const adapter = new RelayerAdapter(paperConfig, undefined, async () => { networkCalls++; throw Error("unexpected fetch"); });
for (const operation of ["registerProxy", "registerSession", "open", "close", "status", "cancel", "stake", "unstake", "claim", "withdraw"] as const) await assert.rejects(adapter.request(operation, {}), /Enabled at Papertrade launch/);
assert.equal(networkCalls, 0);
checks.push("Empty official config rejects every adapter operation before network or signing.");
const now = 1000000;
let journal: Journal = { chainId: 999, account: "test-account-label", configVersion: "test-schema-label", phase: "eligible", intentIds: [], nonces: [], deadlines: [] };
assert.throws(() => transition(journal, { type: "deposit", transaction: "fixture" }, now));
journal = transition(journal, { type: "quote", expires: now + 60000 }, now);
assert.throws(() => transition(journal, { type: "deposit", transaction: "fixture" }, now + 60001));
journal = transition(journal, { type: "deposit", transaction: "fixture" }, now);
journal = transition(journal, { type: "credit", availableUsdc: "1000" }, now);
journal = transition(journal, { type: "authorize", expires: now + 7200000 }, now);
journal = transition(journal, { type: "open", intentIds: ["long-intent", "short-intent"], nonces: ["1", "2"], deadlines: [now + 300000, now + 300000] }, now);
const long = { positionId: "long-position", quantity: "1", entry: "100", receipt: "long-receipt" };
const short = { ...long, positionId: "short-position", receipt: "short-receipt" };
assert.equal(transition(journal, { type: "fills", long }, now).phase, "repairRequired");
assert.equal(transition(journal, { type: "fills", long, short: { ...short, quantity: "2" } }, now).phase, "repairRequired");
const reloaded = transition(journal, { type: "reload" }, now);
assert.equal(reloaded.phase, "reconciling");
assert.throws(() => transition(reloaded, { type: "closeLoser" }, now));
journal = transition(journal, { type: "fills", long, short }, now);
assert.equal(journal.phase, "paired");
assert.throws(() => transition(journal, { type: "loserConfirmed" }, now));
journal = transition(journal, { type: "closeLoser" }, now);
journal = transition(journal, { type: "loserConfirmed" }, now);
journal = transition(journal, { type: "settle", availableUsdc: "900", queuedUsdc: "86" }, now);
journal = transition(journal, { type: "requestStake" }, now);
assert.equal(transition(journal, { type: "walletRejected" }, now).phase, "settledOrQueued");
journal = transition(journal, { type: "stakeConfirmed" }, now);
journal = transition(journal, { type: "requestWithdraw" }, now);
journal = transition(journal, { type: "withdrawSubmitted" }, now);
journal = transition(journal, { type: "withdrawConfirmed" }, now);
assert.equal(journal.queuedUsdc, "86");
assert.throws(() => transition({ ...journal, phase: "settledOrQueued", availableUsdc: "9" }, { type: "requestWithdraw" }, now));
checks.push("Receipt-driven phases, stale quotes, partial/mismatched fills, reload reconciliation, separate wallet stake, withdrawal minimum and retained queue debt.");
console.log(JSON.stringify({ status: "passed", checks }, null, 2));
// Launch-only signing must remain inert with missing official definitions.
const { createMemorySession, signWithWallet } = await import('../src/paper/signing');
assert.throws(() => createMemorySession(), /Enabled at Papertrade launch/);
let walletCalls = 0;
await assert.rejects(signWithWallet({request:async()=>{walletCalls++;throw Error('unexpected wallet call');}}, 'not-used' as `0x${string}`, 'stake', {}), /Enabled at Papertrade launch/);
assert.equal(walletCalls,0);
const { openBlockers } = await import('../src/paper/policy');
const policy = { now, paramsReadAt:now, paramsVerified:true, availableUsdc:1000, marginPerLeg:400, notionalPerLeg:10000, leverage:25, minimumMargin:10, minimumNotional:100, maximumNotional:10000000, maximumLeverage:1000, longHeadroom:100000, shortHeadroom:100000, holderLossBudget:800, queuedUsdc:0, holderQueueLimit:0, existingPositions:0, sessionExpires:now+7200000, intentDeadline:now+300000, observedCloseLatencyMs:100, testedMaximumCloseLatencyMs:1000, actualBustDistance:.0395, emergencyDistance:.01 };
assert.deepEqual(openBlockers(policy),[]);
for (const patch of [{paramsVerified:false},{paramsReadAt:now-31000},{availableUsdc:799},{holderLossBudget:799},{existingPositions:1},{shortHeadroom:9999},{queuedUsdc:1},{sessionExpires:now},{observedCloseLatencyMs:1001},{actualBustDistance:.005}]) assert(openBlockers({...policy,...patch}).length>0);
console.log('Passed: empty-config signing/key generation makes zero wallet calls; official parameter, OI, queue, session, budget and close-safety policy guards.');
